# -*- coding: utf-8 -*-
"""
DMF5 single-screen peptide network vectorisation pipeline (published Fig 3D)
Parse HTML -> reproduce hierarchical clustering (verify original colors) -> locate
the top enriched peptide (anchor) -> composite layout -> 3 edge-version vector
figures (PDF/SVG/EPS/PNG) + GEXF + SVG-export HTML
Input: results/dmf5_network/dmf5_interactive_network.html (generated by pyechart_dmf5.py)
Output: results/dmf5_network/
"""
import os
import re
import time
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
from matplotlib.lines import Line2D
from matplotlib.patches import Patch
import matplotlib.patheffects as pe
from adjustText import adjust_text
from sklearn.cluster import AgglomerativeClustering

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
SEED = 42

TAB20_RAW = [matplotlib.colors.to_hex(c).upper() for c in matplotlib.colormaps["tab20"].colors]
# original COLOR_PALETTE order: tab20 dark shades first, light shades last
PAL12 = TAB20_RAW[::2] + TAB20_RAW[1::2][:2]
TAB20 = PAL12 + TAB20_RAW[1::2][2:]  # all 20 colors, for >12 colored clusters
# recoloring palette: tab20 gray slot moved to the end, so small clusters never
# share the singleton gray
RECOLOR = [c for c in TAB20 if c != "#7F7F7F"] + ["#7F7F7F"]
GRAY = "#9E9E9E"
ANCHOR_COLOR = "#FFD54F"
EDGE_STYLE = {
    1: ("#1a1a1a", 0.9, 0.90),
    2: ("#555555", 0.5, 0.45),
    3: ("#9e9e9e", 0.28, 0.18),
    4: ("#cfcfcf", 0.2, 0.08),
}
LUT_OPACITY = {1.0: 1, 0.8: 2, 0.6: 3, 0.1: 4}
TCR_FROM_HTML = {"#FF0000": "DMF5", "#00FF00": "1G4", "#0000FF": "EBV", "#FFA500": "Flu"}
TCR_SOFT = {"DMF5": "#E53935", "1G4": "#43A047", "EBV": "#1E88E5", "Flu": "#FB8C00"}

CONFIGS = [
    dict(tag="DMF5", mode="cluster", n_clusters=12,
         html=os.path.join(REPO, "results", "dmf5_network", "dmf5_interactive_network.html"),
         csvs=[os.path.join(REPO, "data", "top10000_combine_9mer_2305_DMF5_SCD_R123.csv")],
         versions=["all_edges", "dist_le3", "dist_le2"]),
]
plt.rcParams.update({
    "font.family": "Arial",
    "pdf.fonttype": 42, "ps.fonttype": 42, "svg.fonttype": "none",
})


def parse_html(path):
    with open(path, "r", encoding="utf-8") as f:
        html = f.read()
    ds = html.index('"data":')
    ls = html.index('"links":')
    nodes = []
    for name, size, color, label_body in re.findall(
        r'\{\s*"name":\s*"([^"]+)",[\s\S]*?"symbolSize":\s*([\d.]+),[\s\S]*?"color":\s*"(#[0-9A-Fa-f]{6})"[\s\S]*?"label":\s*\{([^}]*)\}',
        html[ds:ls]):
        nodes.append({"name": name, "color": color.upper(),
                      "label_show": '"show":true' in re.sub(r"\s", "", label_body)})
    edges, mismatch = [], 0
    for s, t, w, op in re.findall(
        r'\{\s*"source":\s*"([^"]+)",\s*"target":\s*"([^"]+)",\s*"lineStyle":\s*\{[\s\S]*?"width":\s*([\d.]+),\s*"opacity":\s*([\d.]+)',
        html[ls:]):
        d = LUT_OPACITY.get(float(op))
        actual = sum(a != b for a, b in zip(s, t))
        if d is None or actual != d:
            mismatch += 1
        edges.append((s, t, actual))
    return nodes, edges, mismatch


def blend(color, alpha, bg="#ffffff"):
    c = np.array(matplotlib.colors.to_rgb(color))
    b = np.array(matplotlib.colors.to_rgb(bg))
    return matplotlib.colors.to_hex((1 - alpha) * b + alpha * c)


def find_anchor(csv_path, candidates):
    """Source CSV is sorted by enrichment; return the first peptide present in the network."""
    df = pd.read_csv(csv_path, usecols=["aa"])
    for aa in df["aa"].dropna().astype(str):
        if aa in candidates:
            return aa
    return None


def save_retry(fig, path, **kw):
    for attempt in range(3):
        try:
            fig.savefig(path, **kw)
            return
        except PermissionError:
            if attempt == 2:
                raise
            time.sleep(1.2)


def make_svg_export_html(src_html, out_path, title):
    with open(src_html, "r", encoding="utf-8") as f:
        html = f.read()
    assert "{renderer: 'canvas'}" in html
    html = html.replace("{renderer: 'canvas'}", "{renderer: 'svg'}")
    m_div = re.search(r"document\.getElementById\('([0-9a-f]+)'\)", html)
    div_id = m_div.group(1)
    toolbar = f"""
<div id="exportBar" style="position:fixed;top:16px;right:16px;z-index:9999;
     font-family:Arial,sans-serif;background:#ffffff;border:1px solid #ccc;
     border-radius:8px;padding:12px 16px;box-shadow:0 2px 8px rgba(0,0,0,.15);max-width:340px;">
  <button onclick="exportSVG()" style="padding:8px 16px;font-size:14px;cursor:pointer;
      background:#1976d2;color:#fff;border:none;border-radius:4px;">Export SVG (vector)</button>
  <p style="font-size:12px;color:#555;margin:8px 0 0;line-height:1.5;">{title}<br>
    Wait 1-2 minutes until the force layout has settled (nodes stop moving), then click.<br>
    The exported SVG is a true vector file; open it in Illustrator / Inkscape and
    re-save as PDF or EPS.</p>
</div>
<script>
function exportSVG() {{
  var svg = document.getElementById('{div_id}').querySelector('svg');
  if (!svg) {{ alert('SVG element not found'); return; }}
  var clone = svg.cloneNode(true);
  clone.setAttribute('xmlns', 'http://www.w3.org/2000/svg');
  var bg = document.createElementNS('http://www.w3.org/2000/svg', 'rect');
  bg.setAttribute('x','0'); bg.setAttribute('y','0');
  bg.setAttribute('width','100%'); bg.setAttribute('height','100%');
  bg.setAttribute('fill','#ffffff');
  clone.insertBefore(bg, clone.firstChild);
  var src = '<?xml version="1.0" encoding="UTF-8"?>\\n' +
            new XMLSerializer().serializeToString(clone);
  var blob = new Blob([src], {{type:'image/svg+xml;charset=utf-8'}});
  var a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = '{title}_echarts.svg';
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  URL.revokeObjectURL(a.href);
}}
</script>
</body>"""
    html = html.replace("</body>", toolbar, 1)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)


for cfg in CONFIGS:
    tag = cfg["tag"]
    sub = os.path.join(REPO, "results", "dmf5_network")
    os.makedirs(sub, exist_ok=True)
    print(f"\n{'='*70}\n[{tag}]")

    nodes_raw, edges_raw, mismatch = parse_html(cfg["html"])
    names = [n["name"] for n in nodes_raw]
    print(f"nodes={len(names)} edges={len(edges_raw)} mismatch={mismatch}")

    G = nx.Graph()
    html_color = {n["name"]: n["color"] for n in nodes_raw}
    label_show = {n["name"]: n["label_show"] for n in nodes_raw}
    for n in nodes_raw:
        G.add_node(n["name"])
    for s, t, d in edges_raw:
        G.add_edge(s, t, hamming=d)
    degree = dict(G.degree())
    max_dist = max(d for _, _, d in G.edges(data="hamming"))

    # ---- Clustering / TCR grouping ----
    if cfg["mode"] == "cluster":
        seqs = names
        n = len(seqs)
        H = np.zeros((n, n))
        for i in range(n):
            for j in range(i + 1, n):
                d = sum(a != b for a, b in zip(seqs[i], seqs[j]))
                H[i, j] = H[j, i] = d
        cl = AgglomerativeClustering(n_clusters=cfg["n_clusters"],
                                     metric="precomputed", linkage="average")
        labels = cl.fit_predict(H)
        cluster_of = {seqs[i]: int(labels[i]) for i in range(n)}
        sizes = pd.Series(list(labels)).value_counts().to_dict()

        # Verify: expected color counts vs actual HTML color counts
        pal = TAB20[:12]
        if cfg["n_clusters"] <= 12:
            expect = {pal[i]: sizes.get(i, 0) for i in range(cfg["n_clusters"])}
        else:
            expect = {}
            for i in range(cfg["n_clusters"]):
                expect[pal[i % 12]] = expect.get(pal[i % 12], 0) + sizes.get(i, 0)
        actual = {}
        for nm in names:
            actual[html_color[nm]] = actual.get(html_color[nm], 0) + 1
        match = all(expect.get(c, 0) == v for c, v in actual.items())
        print(f"cluster verify vs HTML colors: {'MATCH' if match else 'MISMATCH'}")
        if not match and cfg["n_clusters"] <= 12:
            # Fallback: HTML colors serve as cluster ids (1:1 palette)
            print("  -> fallback to HTML colors as cluster id")
            cluster_of = {nm: pal.index(html_color[nm]) for nm in names}
            sizes = pd.Series(list(cluster_of.values())).value_counts().to_dict()

        # Recolor: clusters in size-descending order take tab20 (gray last);
        # singleton clusters are gray
        order = sorted([c for c in sizes if sizes[c] >= 2],
                       key=lambda c: -sizes[c])
        color_of = {}
        for nm in names:
            c = cluster_of[nm]
            color_of[nm] = RECOLOR[order.index(c)] if sizes[c] >= 2 else GRAY
        legend_nodes = [(f"Cluster {i+1} (n = {sizes[c]})", RECOLOR[i])
                        for i, c in enumerate(order)]
        n_single = sum(1 for c in sizes if sizes[c] == 1)
        if n_single:
            legend_nodes.append((f"Singleton clusters (n = {n_single})", GRAY))
    else:
        tcr_of = {nm: TCR_FROM_HTML[html_color[nm]] for nm in names}
        color_of = {nm: TCR_SOFT[tcr_of[nm]] for nm in names}
        tc = pd.Series(list(tcr_of.values())).value_counts().to_dict()
        legend_nodes = [(f"{t}-selected (n = {tc[t]})", TCR_SOFT[t]) for t in TCR_SOFT]

    # ---- Anchor: top enriched peptide ----
    anchors = []
    if cfg["mode"] == "cluster":
        a = find_anchor(cfg["csvs"][0], set(names))
        if a is None:
            a = max(names, key=lambda x: degree[x])
        anchors = [a]
    else:
        for t, csvp in zip(("DMF5", "1G4", "EBV", "Flu"), cfg["csvs"]):
            group = {nm for nm in names if tcr_of[nm] == t}
            if group:
                a = find_anchor(csvp, group)
                if a is None:
                    a = max(group, key=lambda x: degree[x])
                anchors.append(a)
    print(f"anchors (top enriched): {anchors}")

    # ---- Composite layout ----
    K = 3 if max_dist >= 4 else 2
    HK = nx.Graph()
    HK.add_nodes_from(G.nodes)
    for u, v, d in G.edges(data="hamming"):
        if d <= K:
            HK.add_edge(u, v)
    main_comp = max(nx.connected_components(HK), key=len)
    isolates = sorted(n for n in G.nodes if G.degree(n) == 0)

    L = nx.Graph()
    L.add_nodes_from(G.nodes)
    for u, v, d in G.edges(data="hamming"):
        if d <= K:
            L.add_edge(u, v, spring_w=1.0 / d ** 3)
        elif u not in main_comp or v not in main_comp:
            L.add_edge(u, v, spring_w=1.0 / (K + 1) ** 3)

    n_nodes = len(names)
    k_layout = 0.65 if n_nodes <= 40 else (0.55 if n_nodes <= 160 else 0.42)
    pos = nx.spring_layout(L, k=k_layout, iterations=2000, seed=SEED, weight="spring_w")
    main_xy = np.array([pos[n] for n in main_comp])
    c = main_xy.mean(axis=0)
    r_max = np.linalg.norm(main_xy - c, axis=1).max()
    if isolates:
        for i, nm in enumerate(isolates):
            ang = np.pi / 2 + 2 * np.pi * i / len(isolates)
            pos[nm] = (c[0] + r_max * 1.18 * np.cos(ang),
                       c[1] + r_max * 1.18 * np.sin(ang))

    # Layout diagnostics
    all_xy = np.array([pos[n] for n in names])
    span = max(np.ptp(all_xy[:, 0]), np.ptp(all_xy[:, 1]))
    ppu = 7.09 * 72 * 0.92 / span
    diag = []
    for d in range(1, max_dist + 1):
        lens = [np.hypot(pos[u][0] - pos[v][0], pos[u][1] - pos[v][1]) * ppu
                for u, v, dd in G.edges(data="hamming") if dd == d]
        if lens:
            diag.append(f"d{d}: p10={np.percentile(lens,10):.1f}/med={np.median(lens):.1f}pt")
    print("layout: " + " | ".join(diag) + f" | main_comp={len(main_comp)} isolates={len(isolates)}")

    # ---- Save tables ----
    pd.DataFrame([{"name": nm, "cluster": cluster_of[nm] if cfg["mode"] == "cluster" else tcr_of[nm],
                   "color": color_of[nm], "label_show": int(label_show[nm]),
                   "degree": degree[nm], "is_anchor": int(nm in anchors)} for nm in names]).to_csv(
        os.path.join(sub, "nodes.csv"), index=False)
    pd.DataFrame(edges_raw, columns=["source", "target", "hamming"]).to_csv(
        os.path.join(sub, "links.csv"), index=False)
    pd.DataFrame([{"name": nm, "x": pos[nm][0], "y": pos[nm][1]} for nm in names]).to_csv(
        os.path.join(sub, "layout_positions.csv"), index=False)

    # ---- Plotting ----
    node_s = 55 if n_nodes <= 40 else (30 if n_nodes <= 160 else 22)
    label_fs = 5.5
    anchor_fs = 7

    for suffix in cfg["versions"]:
        keep = {"all_edges": list(range(1, max_dist + 1)),
                "dist_le3": [1, 2, 3], "dist_le2": [1, 2]}[suffix]
        keep = [d for d in keep if d <= max_dist]
        fig, ax = plt.subplots(figsize=(7.09, 7.09))

        segs, cols, lws = [], [], []
        for u, v, d in G.edges(data="hamming"):
            if d not in keep:
                continue
            cc, w, a = EDGE_STYLE[d]
            segs.append([pos[u], pos[v]])
            cols.append(blend(cc, a))
            lws.append(w)
        ax.add_collection(LineCollection(segs, colors=cols, linewidths=lws,
                                         capstyle="round", zorder=1))

        reg = [i for i, nm in enumerate(names) if nm not in anchors]
        anch = [i for i, nm in enumerate(names) if nm in anchors]
        if reg:
            ax.scatter(all_xy[reg, 0], all_xy[reg, 1], s=node_s,
                       c=[color_of[names[i]] for i in reg], edgecolors="white",
                       linewidths=0.4, zorder=3)
        if anch:
            # anchor nodes drawn above ordinary labels so the gold highlight is
            # never covered by a label
            ax.scatter(all_xy[anch, 0], all_xy[anch, 1], s=node_s * 3,
                       c=ANCHOR_COLOR, edgecolors="#000000", linewidths=1.1,
                       zorder=4.6)

        texts = []
        for nm in names:
            if nm in anchors:
                continue
            if label_show[nm] or degree[nm] == 0:
                texts.append(ax.text(pos[nm][0], pos[nm][1], nm, fontsize=label_fs,
                                     color="#212121", zorder=4,
                                     path_effects=[pe.withStroke(linewidth=1.6, foreground="white")]))
        # Anchor guard ring: avoidance points around each anchor keep adjust_text
        # from dropping labels onto the enlarged gold anchor node
        # (in 4TCR_1G4 the YLWGRESQM label once covered the anchor and misled readers)
        avoid_xy = np.array([pos[nm] for nm in names])
        for a_nm in anchors:
            ap = np.array(pos[a_nm])
            for r in (0.02, 0.05, 0.10):
                ang = np.linspace(0, 2 * np.pi, 16, endpoint=False)
                avoid_xy = np.vstack([avoid_xy, ap + r * np.column_stack([np.cos(ang), np.sin(ang)])])
        if texts:
            # adjustText>=1.4: avoidance points must be passed as separate x= / y=
            # arrays, otherwise they are silently ignored
            adjust_text(texts, x=avoid_xy[:, 0], y=avoid_xy[:, 1], ax=ax,
                        expand=(1.15, 1.35),
                        force_text=(0.35, 0.55), force_static=(0.25, 0.45),
                        avoid_self=True, ensure_inside_axes=True)
        for a_nm in anchors:
            ax.text(pos[a_nm][0], pos[a_nm][1] + 0.045, a_nm, fontsize=anchor_fs,
                    fontweight="bold", ha="center", color="#000000", zorder=5,
                    path_effects=[pe.withStroke(linewidth=1.8, foreground="white")])

        edge_handles = [
            Line2D([0], [0], color=blend(EDGE_STYLE[d][0], EDGE_STYLE[d][2]),
                   lw=EDGE_STYLE[d][1], label=f"Hamming distance = {d}")
            for d in keep
        ]
        node_handles = [Patch(facecolor=c, label=l) for l, c in legend_nodes]
        node_handles.append(Patch(facecolor=ANCHOR_COLOR, edgecolor="#000000",
                                  label="Top enriched" + ("s" if len(anchors) > 1 else "")))
        leg1 = ax.legend(handles=edge_handles, title="Edges", loc="upper left",
                         frameon=True, fontsize=6, title_fontsize=6.5,
                         borderpad=0.6, handlelength=1.8, framealpha=1.0)
        leg1.get_frame().set_edgecolor("#cccccc")
        ax.add_artist(leg1)
        leg2 = ax.legend(handles=node_handles, title="Nodes", loc="lower left",
                         frameon=True, fontsize=6, title_fontsize=6.5,
                         borderpad=0.6, handlelength=1.2, framealpha=1.0)
        leg2.get_frame().set_edgecolor("#cccccc")

        ax.set_xticks([]); ax.set_yticks([])
        for s in ax.spines.values():
            s.set_visible(False)
        ax.margins(0.04)

        for ext in ("pdf", "svg", "eps", "png"):
            out = os.path.join(sub, f"peptide_network_{tag}_{suffix}.{ext}")
            save_retry(fig, out, format=ext, dpi=600 if ext == "png" else None,
                       bbox_inches="tight", pad_inches=0.02)
        plt.close(fig)
        print(f"saved peptide_network_{tag}_{suffix}.pdf/.svg/.eps/.png")

    # ---- GEXF ----
    GX = nx.Graph()
    for nm in names:
        rgb = tuple(int(color_of[nm][i:i + 2], 16) for i in (1, 3, 5))
        GX.add_node(nm, label=nm,
                    group=cluster_of[nm] if cfg["mode"] == "cluster" else tcr_of[nm],
                    degree=degree[nm], is_anchor=int(nm in anchors),
                    viz={"color": {"r": rgb[0], "g": rgb[1], "b": rgb[2], "a": 1.0},
                         "position": {"x": float(pos[nm][0]), "y": float(pos[nm][1]), "z": 0.0},
                         "size": 60.0 if nm in anchors else 20.0})
    for u, v, d in G.edges(data="hamming"):
        GX.add_edge(u, v, hamming=d, weight=1.0 / d)
    gexf_path = os.path.join(sub, f"peptide_network_{tag}.gephi.gexf")
    nx.write_gexf(GX, gexf_path, version="1.2draft")

    # ---- SVG export HTML ----
    make_svg_export_html(cfg["html"], os.path.join(sub, f"{tag}_svg_export.html"), tag)

    print(f"saved gexf + svg_export.html")

print("\nALL DONE")
