# -*- coding: utf-8 -*-
"""
DMF5 peptide network - wide light publication figure (PDF / SVG / EPS / PNG)
Data: results/dmf5_network/nodes.csv + links.csv (generated by pipeline_all_networks.py)
Layout: d<=3 spring (seed=42) -> rotate 90 deg clockwise (tall cluster lies down to
        fit the wide canvas, near-isotropic rendering)
        -> hull-ray placement of the outer ring in render space (pure isolates +
        far groups) with even visual gaps; d=4 bridge satellites keep their spring
        positions
Output: results/dmf5_network/peptide_network_DMF5_{all_edges,dist_le3,dist_le2}_light.* (shared layout)
        results/dmf5_network/peptide_network_DMF5_dist_eq1_light.* (nearest-neighbour islands, rendered separately)
Edge style: d=1-2 solid dark (near-black/dark gray), d=3-4 pale (light/very light gray)
        - close neighbours stand out, distant relations fade into the background
Granularity (shared layout, progressively denser for comparison): d<=2 main component
        117 (family structure); d<=3 main component 271 (recommended main figure);
        d<=4 full 5,531 edges
dist_eq1 (nearest-neighbour islands): of 295 nodes only 61 have a d=1 neighbour
        (25 components: 6/5/3/3/3/3 + 19 pairs); the other 234 keep their cluster
        colors but are smaller, paler and unlabelled - every point's color still
        maps to its cluster while the island hierarchy is preserved; d=1 edges are
        drawn above the nodes
        (the spring layout pulls d=1 pairs to < node diameter; drawn below, 37% of
        the edges would be completely hidden)
Anchor: star TLLGFGSCV = top enriched peptide (degree=77), filled with the DMF5 TCR
        color (#E53935, matching the Combined figure)
Data scale: raw CSV 10,000 rows (7,962 standard 9-mers); network takes the top 300
        deduplicated = 295 nodes
Full distribution: of 43,365 pairs d=1:38 (0.09%) d=2:293 (0.68%) d=3:1410 (3.3%)
        d=4:3790 (8.7%) d>=5:37834 (87%) - versus the Flu library where d<=3 covers
        45.3%, DMF5 has only 4.0%: extremely sparse
"""
import os
import time
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
from matplotlib.lines import Line2D
from matplotlib.patches import Patch
import matplotlib.patheffects as pe
from scipy.spatial import ConvexHull
from adjustText import adjust_text

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
SUB = os.path.join(REPO, "results", "dmf5_network")
TAG = "DMF5"
ANCHOR = "TLLGFGSCV"          # top enriched peptide in the source CSV (degree=77), star, DMF5 TCR red fill
SEED = 42

# ---------------- Tunable parameters ----------------
FIGSIZE_IN = (7.09, 4.92)     # 180 x 125 mm wide two-column figure
NODE_SIZE = 22                # small dots for 295 nodes
ANCHOR_NODE_SIZE = 60
STAR_FACTOR = 2.2             # star area multiplier (at equal s a star looks much smaller than a circle)
LABEL_FONTSIZE = 5.5
GAP_PT = 14.0                 # render-space gap between the ring and the main-cluster hull (pt), ~2.6 node diameters
FAR_FACTOR = 1.3              # groups with centroid > 1.3*r_max from the main-cluster center count as far groups

LIGHT_KEEP = 0.55
LIGHT_GRAY_KEEP = 0.75
TCR_COLOR = "#E53935"            # DMF5 TCR color (matching the 4TCR_Combined figure), top enriched anchor
ANCHOR_ARROW_COLOR = "#8E2321"   # dark red annotation color (darkened TCR color)
ANN_DX, ANN_DY = 0.038, -0.058   # anchor annotation text offset relative to the anchor

LIGHT_EDGE_STYLE = {           # (color, width, keep fraction): d=1-2 solid dark, d=3-4 pale
    1: ("#1a1a1a", 1.0, 1.00),
    2: ("#404040", 0.72, 0.82),
    3: ("#a6a6a6", 0.30, 0.35),
    4: ("#c9c9c9", 0.22, 0.16),
}
VERSIONS = {"all_edges": [1, 2, 3, 4], "dist_le3": [1, 2, 3], "dist_le2": [1, 2]}

plt.rcParams.update({
    "font.family": "Arial",
    "pdf.fonttype": 42, "ps.fonttype": 42, "svg.fonttype": "none",
})

# ---------------- Data ----------------
nodes_df = pd.read_csv(os.path.join(SUB, "nodes.csv"))
links_df = pd.read_csv(os.path.join(SUB, "links.csv"))
G = nx.Graph()
for _, r in nodes_df.iterrows():
    G.add_node(r["name"], cluster=int(r["cluster"]), color=r["color"],
               label_show=bool(r["label_show"]), degree=int(r["degree"]))
for _, r in links_df.iterrows():
    G.add_edge(r["source"], r["target"], hamming=int(r["hamming"]))
K = 3

# ---------------- Layout: d<=3 spring -> rotate 90 deg ----------------
HK = nx.Graph(); HK.add_nodes_from(G.nodes)
for u, v, d in G.edges(data="hamming"):
    if d <= K:
        HK.add_edge(u, v)
main_comp = max(nx.connected_components(HK), key=len)

L = nx.Graph(); L.add_nodes_from(G.nodes)
for u, v, d in G.edges(data="hamming"):
    if d <= K:
        L.add_edge(u, v, spring_w=1.0 / d ** 3)
    elif u not in main_comp or v not in main_comp:
        L.add_edge(u, v, spring_w=1.0 / (K + 1) ** 3)

pos = nx.spring_layout(L, k=0.42, iterations=2000, seed=SEED, weight="spring_w")
# Rotate 90 deg clockwise: the tall main cluster lies down and the wide canvas
# renders near-isotropically (avoiding a 2.5x x-stretch)
pos = {n: (pos[n][1], -pos[n][0]) for n in pos}

main_xy = np.array([pos[n] for n in main_comp])
_c = main_xy.mean(axis=0)
_r_max = np.linalg.norm(main_xy - _c, axis=1).max()

# ---------------- Ring groups: pure isolates (deg=0) + far groups ----------------
nonmain = [n for n in G.nodes if n not in main_comp]
S = G.subgraph(nonmain)
ring_groups, kept = [], []
for comp in nx.connected_components(S):
    cen = np.mean([pos[n] for n in comp], axis=0)
    far = np.linalg.norm(cen - _c) > FAR_FACTOR * _r_max
    if len(comp) == 1 and G.degree(next(iter(comp))) == 0:
        ring_groups.append(sorted(comp))          # pure isolate
    elif len(comp) > 1 and far:
        ring_groups.append(sorted(comp))          # far group flung away by the spring layout
    else:
        kept.append(sorted(comp))                 # d=4 bridge satellites keep spring positions
print(f"ring groups ({len(ring_groups)}): {[g[0] + ('+' + str(len(g)-1) if len(g) > 1 else '') for g in ring_groups]}")

# ---------------- Ring placement via hull rays in render space ----------------
# 1) render scale ptx/pty: points per data unit once the content (ring + label
#    margins) fills the canvas
blob = list(main_comp) + [n for g in kept for n in g]
blob_xy = np.array([pos[n] for n in blob])
cx, cy = blob_xy.mean(axis=0)
W_pt = FIGSIZE_IN[0] * 72 * 0.94
H_pt = FIGSIZE_IN[1] * 72 * 0.94
span0x, span0y = np.ptp(blob_xy[:, 0]), np.ptp(blob_xy[:, 1])
ptx, pty = W_pt / span0x, H_pt / span0y
for _ in range(4):
    spanx = span0x + 2 * (GAP_PT + 18) / ptx      # 18pt: outward margin for ring-node labels
    spany = span0y + 2 * (GAP_PT + 18) / pty
    ptx, pty = W_pt / spanx, H_pt / spany
print(f"render scale: ptx={ptx:.0f} pty={pty:.0f} (ratio {ptx/pty:.2f}, closer to 1 is more isotropic)")

# 2) render-space convex hull of main cluster + satellites
Rb = np.array([((pos[n][0] - cx) * ptx, (pos[n][1] - cy) * pty) for n in blob])
hull_pts = Rb[ConvexHull(Rb).vertices]
hull_r_max = np.linalg.norm(hull_pts, axis=1).max()

def hull_ray_radius(phi):
    """Radius (render pt) where the ray from the centroid at angle phi crosses the hull"""
    d = np.array([np.cos(phi), np.sin(phi)])
    P, Q = hull_pts, np.roll(hull_pts, -1, axis=0)
    ts = []
    for p, q in zip(P, Q):
        e = q - p
        A = np.array([[d[0], -e[0]], [d[1], -e[1]]])
        if abs(np.linalg.det(A)) < 1e-9:
            continue
        t, s = np.linalg.solve(A, p)
        if t > 1e-9 and -1e-9 <= s <= 1 + 1e-9:
            ts.append(t)
    return min(ts) if ts else 0.0

def ring_slot_xy(phi):
    t = max(hull_ray_radius(phi) + GAP_PT, 0.45 * hull_r_max + GAP_PT)
    return (cx + t * np.cos(phi) / ptx, cy + t * np.sin(phi) / pty)

# 3) Adaptive slots: 6 sectors of 60 deg each, picking the direction where ring
#    points sit closest to the main component's mass (avoiding concave bays).
#    Closeness is scored on main-component nodes only (d=4 satellites have no edge
#    in the le3 version and would float, misrepresenting the outline); the placement
#    radius still uses the full blob hull so nothing overlaps
Rb_main = np.array([((pos[n][0] - cx) * ptx, (pos[n][1] - cy) * pty) for n in main_comp])

def clearance_at(phi):
    t = hull_ray_radius(phi) + GAP_PT + 18.0
    R = np.array([t * np.cos(phi), t * np.sin(phi)])
    return float(np.min(np.linalg.norm(Rb_main - R, axis=1))), t

N = len(ring_groups)
slots, used_phis = [], []
for sec in range(N):
    lo, hi = 2 * np.pi * sec / N, 2 * np.pi * (sec + 1) / N
    best_phi, best_cl = None, 1e9
    for phi_d in range(int(np.degrees(lo)), int(np.degrees(hi))):
        phi = np.deg2rad(phi_d)
        cl, t = clearance_at(phi)
        if t < 0.5 * hull_r_max:
            continue
        # keep >= 20 deg separation from already-placed slots (wrapping across 0)
        if any(abs((phi - p + np.pi) % (2 * np.pi) - np.pi) < np.deg2rad(20) for p in used_phis):
            continue
        if cl < best_cl:
            best_cl, best_phi = cl, phi
    if best_phi is None:                        # whole sector excluded by spacing -> relax it
        for phi_d in range(int(np.degrees(lo)), int(np.degrees(hi))):
            phi = np.deg2rad(phi_d)
            cl, t = clearance_at(phi)
            if t >= 0.5 * hull_r_max and cl < best_cl:
                best_cl, best_phi = cl, phi
    slots.append(best_phi)
    used_phis.append(best_phi)

def rangle(g):
    cen = np.mean([pos[n] for n in g], axis=0)
    return np.arctan2((cen[1] - cy) * pty, (cen[0] - cx) * ptx) % (2 * np.pi)

ring_groups.sort(key=rangle)
slots.sort()
for g, phi in zip(ring_groups, slots):
    if len(g) == 1:
        r_g = 3.0
    else:
        cen = np.mean([pos[n] for n in g], axis=0)
        r_g = max(np.hypot((pos[n][0] - cen[0]) * ptx, (pos[n][1] - cen[1]) * pty)
                  for n in g) + 3.0
    t = hull_ray_radius(phi) + GAP_PT + r_g
    tx, ty = cx + t * np.cos(phi) / ptx, cy + t * np.sin(phi) / pty
    print(f"  slot {np.degrees(phi):5.1f}deg (hull_r={hull_ray_radius(phi):5.0f}pt cl={clearance_at(phi)[0]:5.0f}pt) <- {g[0]}{'+' + str(len(g)-1) if len(g) > 1 else ''}")
    if len(g) == 1:
        pos[g[0]] = (tx, ty)
    else:
        # move the whole small group to its slot, preserving internal shape
        cen = np.mean([pos[n] for n in g], axis=0)
        offs = {n: (pos[n][0] - cen[0], pos[n][1] - cen[1]) for n in g}
        m = max(np.linalg.norm(o) for o in offs.values())
        scale = min(1.0, 0.05 / m) if m > 0 else 1.0
        for n in g:
            pos[n] = (tx + offs[n][0] * scale, ty + offs[n][1] * scale)

# Anchor annotation direction: scan 16 directions around the anchor for the emptiest
# spot (the anchor sits inside the dense core)
others_xy = np.array([pos[n] for n in G.nodes if n != ANCHOR])
best_phi, best_cl = 0.0, -1.0
for k in range(16):
    phi = 2 * np.pi * k / 16
    u = np.array([np.cos(phi), np.sin(phi)])
    a0 = np.array(pos[ANCHOR]) + 0.062 * u
    a1 = np.array(pos[ANCHOR]) + 0.095 * u
    cl = min(float(np.min(np.hypot((others_xy[:, 0] - a0[0]) * ptx,
                                    (others_xy[:, 1] - a0[1]) * pty))),
             float(np.min(np.hypot((others_xy[:, 0] - a1[0]) * ptx,
                                    (others_xy[:, 1] - a1[1]) * pty))))
    if cl > best_cl:
        best_cl, best_phi = cl, phi
ANN_DX, ANN_DY = 0.062 * np.cos(best_phi), 0.062 * np.sin(best_phi)
ANN_HA = "left" if np.cos(best_phi) > 0.3 else ("right" if np.cos(best_phi) < -0.3 else "center")
ANN_VA = "bottom" if np.sin(best_phi) > 0.3 else ("top" if np.sin(best_phi) < -0.3 else "center")
print(f"anchor ann: dir={np.degrees(best_phi):.0f}deg clearance={best_cl:.0f}pt ha={ANN_HA} va={ANN_VA}")

pd.DataFrame([{"name": n, "x": pos[n][0], "y": pos[n][1]} for n in G.nodes]).to_csv(
    os.path.join(SUB, "layout_positions_wide.csv"), index=False)

node_names = list(G.nodes)
xy = np.array([pos[n] for n in node_names])

def blend(color, alpha, bg="#ffffff"):
    c = np.array(matplotlib.colors.to_rgb(color))
    b = np.array(matplotlib.colors.to_rgb(bg))
    return matplotlib.colors.to_hex((1 - alpha) * b + alpha * c)

def lighten(color, keep=LIGHT_KEEP):
    return blend(color, keep)

# ---------------- Legend data ----------------
cl_size = nodes_df["cluster"].value_counts()
cl_color = nodes_df.groupby("cluster")["color"].first()
order = sorted([c for c in cl_size.index if cl_size[c] >= 2], key=lambda c: -cl_size[c])
legend_nodes = [(f"Cluster {i + 1} (n = {cl_size[c]})", cl_color[c]) for i, c in enumerate(order)]
n_single = int(sum(1 for c in cl_size.index if cl_size[c] == 1))
if n_single:
    legend_nodes.append((f"Singleton clusters (n = {n_single})", "#9E9E9E"))

ring_members = {n for g in ring_groups for n in g}
def show_label(n):
    return G.nodes[n]["label_show"] or G.degree(n) == 0 or n in ring_members

def save_retry(fig, path, **kw):
    for attempt in range(3):
        try:
            fig.savefig(path, **kw)
            return
        except PermissionError:
            if attempt == 2:
                raise
            time.sleep(1.2)

# ---------------- Plotting ----------------
anchor_i = node_names.index(ANCHOR)
for suffix, keep in VERSIONS.items():
    fig, ax = plt.subplots(figsize=FIGSIZE_IN)
    ax.set_position([0, 0, 1, 1])   # axes fill the figure (default subplot margins leave content at 77%)
    ax.set_facecolor("white")

    segs, cols, lws = [], [], []
    for u, v, d in G.edges(data="hamming"):
        if d not in keep:
            continue
        c, w, a = LIGHT_EDGE_STYLE[d]
        segs.append([pos[u], pos[v]])
        cols.append(blend(c, a))
        lws.append(w)
    ax.add_collection(LineCollection(segs, colors=cols, linewidths=lws,
                                     capstyle="round", zorder=1))

    reg = [i for i in range(len(node_names)) if i != anchor_i]
    face_reg = []
    for i in reg:
        n = node_names[i]
        if cl_size[int(G.nodes[n]["cluster"])] == 1:
            face_reg.append(lighten("#9E9E9E", LIGHT_GRAY_KEEP))
        else:
            face_reg.append(lighten(G.nodes[n]["color"]))
    ax.scatter(xy[reg, 0], xy[reg, 1], s=NODE_SIZE, c=face_reg,
               edgecolors="white", linewidths=0.4, zorder=3)
    ax.scatter([xy[anchor_i, 0]], [xy[anchor_i, 1]], s=ANCHOR_NODE_SIZE * STAR_FACTOR,
               marker="*", c=TCR_COLOR,
               edgecolors="#000000", linewidths=1.0, zorder=4.6)

    # --- Labels + adjustText ---
    texts = []
    for n in node_names:
        if n == ANCHOR:
            continue
        if show_label(n):
            texts.append(ax.text(pos[n][0], pos[n][1], n, fontsize=LABEL_FONTSIZE,
                                 color="#212121", zorder=4,
                                 path_effects=[pe.withStroke(linewidth=1.6, foreground="white")]))
    avoid_xy = xy.copy()
    ap = np.array(pos[ANCHOR])
    for r in (0.02, 0.05, 0.10):
        ang = np.linspace(0, 2 * np.pi, 16, endpoint=False)
        avoid_xy = np.vstack([avoid_xy, ap + r * np.column_stack([np.cos(ang), np.sin(ang)])])
    ann_x = pos[ANCHOR][0] + ANN_DX
    ann_y = pos[ANCHOR][1] + ANN_DY
    # annotation text-box extent (expanded outward from the anchor per ha/va), added
    # to the avoidance set
    bw, bh = 0.075, 0.030
    bx0 = ann_x if ANN_HA == "left" else (ann_x - bw if ANN_HA == "right" else ann_x - bw / 2)
    bx1 = ann_x + bw if ANN_HA == "left" else (ann_x if ANN_HA == "right" else ann_x + bw / 2)
    by0 = ann_y if ANN_VA == "bottom" else (ann_y - bh if ANN_VA == "top" else ann_y - bh / 2)
    by1 = ann_y + bh if ANN_VA == "bottom" else (ann_y if ANN_VA == "top" else ann_y + bh / 2)
    for fx in np.linspace(bx0, bx1, 7):
        for fy in np.linspace(by0, by1, 4):
            avoid_xy = np.vstack([avoid_xy, [fx, fy]])
    for t in np.linspace(0.2, 0.8, 4):
        avoid_xy = np.vstack([avoid_xy,
                              [pos[ANCHOR][0] + t * (ann_x - pos[ANCHOR][0]),
                               pos[ANCHOR][1] + t * (ann_y - pos[ANCHOR][1])]])
    if texts:
        adjust_text(texts, x=avoid_xy[:, 0], y=avoid_xy[:, 1], ax=ax,
                    expand=(1.15, 1.35),
                    force_text=(0.35, 0.55), force_static=(0.25, 0.45),
                    avoid_self=True, ensure_inside_axes=True)

    # --- Anchor arrow annotation: dark red (darkened TCR color), pointing at the star ---
    ax.annotate(
        f"Top enriched\n{ANCHOR}", xy=(pos[ANCHOR][0], pos[ANCHOR][1]),
        xytext=(ann_x, ann_y),
        fontsize=7.5, fontweight="bold", color=ANCHOR_ARROW_COLOR,
        ha=ANN_HA, va=ANN_VA, zorder=5.6,
        path_effects=[pe.withStroke(linewidth=1.8, foreground="white")],
        arrowprops=dict(arrowstyle="-|>", color=ANCHOR_ARROW_COLOR,
                        lw=1.1, mutation_scale=13, shrinkA=2, shrinkB=7),
        annotation_clip=False)

    # --- Legends: outside the canvas on the right (content fills the canvas,
    # no large free area inside) ---
    edge_handles = [
        Line2D([0], [0], color=blend(LIGHT_EDGE_STYLE[d][0], LIGHT_EDGE_STYLE[d][2]),
               lw=LIGHT_EDGE_STYLE[d][1], label=f"Hamming distance = {d}")
        for d in keep
    ]
    node_handles = [Patch(facecolor=lighten(c), label=l) for l, c in legend_nodes]
    marker_kw = dict(linestyle="none", markeredgecolor="#000000", markeredgewidth=0.7)
    node_handles.append(Line2D([0], [0], marker="*", markersize=9,
                               markerfacecolor=TCR_COLOR,
                               label=f"Top enriched {ANCHOR}", **marker_kw))
    leg1 = ax.legend(handles=edge_handles, title="Edges", loc="center left",
                     bbox_to_anchor=(1.02, 0.76),
                     frameon=True, fontsize=6, title_fontsize=6.5,
                     borderpad=0.6, handlelength=1.8, framealpha=1.0)
    leg1.get_frame().set_edgecolor("#cccccc")
    ax.add_artist(leg1)
    leg2 = ax.legend(handles=node_handles, title="Nodes", loc="center left",
                     bbox_to_anchor=(1.02, 0.36),
                     frameon=True, fontsize=6, title_fontsize=6.5,
                     borderpad=0.6, handlelength=1.5, handletextpad=0.7,
                     labelspacing=0.8, framealpha=1.0)
    leg2.get_frame().set_edgecolor("#cccccc")

    ax.set_xticks([]); ax.set_yticks([])
    for s in ax.spines.values():
        s.set_visible(False)
    ax.margins(0.03)

    for ext in ("pdf", "svg", "eps", "png"):
        out = os.path.join(SUB, f"peptide_network_{TAG}_{suffix}_light.{ext}")
        save_retry(fig, out, format=ext, dpi=600 if ext == "png" else None,
                   bbox_inches="tight", pad_inches=0.02)
    plt.close(fig)
    print(f"saved {suffix}_light")

# ---------------- dist_eq1: nearest-neighbour islands (rendered separately) ----------------
# Of 295 nodes only 61 have a d=1 neighbour -> normal colors + labels; the other 234
# keep cluster colors (smaller, paler, unlabelled) so the island hierarchy is
# preserved while every point's color still maps to its cluster
H1 = nx.Graph(); H1.add_nodes_from(G.nodes)
for u, v, d in G.edges(data="hamming"):
    if d == 1:
        H1.add_edge(u, v)
d1_nodes = {n for n in G.nodes if H1.degree(n) > 0}
plain = [n for n in node_names if n not in d1_nodes]
print(f"dist_eq1: {len(d1_nodes)} nodes with d=1 neighbour, {len(plain)} isolated at d=1")

fig, ax = plt.subplots(figsize=FIGSIZE_IN)
ax.set_position([0, 0, 1, 1])
ax.set_facecolor("white")

# No d=1 neighbour: cluster-colored but smaller and paler (background layer)
pxy = np.array([pos[n] for n in plain])
face_plain = []
for n in plain:
    if cl_size[int(G.nodes[n]["cluster"])] == 1:
        face_plain.append(lighten("#9E9E9E", LIGHT_GRAY_KEEP))
    else:
        face_plain.append(lighten(G.nodes[n]["color"], 0.42))
ax.scatter(pxy[:, 0], pxy[:, 1], s=14, c=face_plain, edgecolors="white",
           linewidths=0.3, zorder=2.5)

# Has a d=1 neighbour: normal cluster colors
reg = [n for n in d1_nodes if n != ANCHOR]
rx = np.array([pos[n] for n in reg])
face_reg = []
for n in reg:
    if cl_size[int(G.nodes[n]["cluster"])] == 1:
        face_reg.append(lighten("#9E9E9E", LIGHT_GRAY_KEEP))
    else:
        face_reg.append(lighten(G.nodes[n]["color"]))
ax.scatter(rx[:, 0], rx[:, 1], s=NODE_SIZE, c=face_reg,
           edgecolors="white", linewidths=0.4, zorder=3.0)

# d=1 edges drawn above the nodes: in the spring layout d=1 pairs sit closer than
# two node diameters (median 6.6pt); drawn below, 37% of the edges would be
# completely covered by nodes
segs = [[pos[u], pos[v]] for u, v, d in G.edges(data="hamming") if d == 1]
ax.add_collection(LineCollection(segs, colors="#1a1a1a", linewidths=1.3,
                                 capstyle="round", zorder=3.4))

ax.scatter([pos[ANCHOR][0]], [pos[ANCHOR][1]], s=ANCHOR_NODE_SIZE * STAR_FACTOR,
           marker="*", c=TCR_COLOR,
           edgecolors="#000000", linewidths=1.0, zorder=4.6)

# Labels: only the 61 d=1 nodes (rest unlabelled to highlight the islands); slightly
# smaller font + stronger repulsion to fight crowding in the dense core
texts = [ax.text(pos[n][0], pos[n][1], n, fontsize=5.0,
                 color="#212121", zorder=4,
                 path_effects=[pe.withStroke(linewidth=1.3, foreground="white")])
         for n in d1_nodes if n != ANCHOR]
avoid_xy = xy.copy()
ap = np.array(pos[ANCHOR])
for r in (0.02, 0.05, 0.10):
    ang = np.linspace(0, 2 * np.pi, 16, endpoint=False)
    avoid_xy = np.vstack([avoid_xy, ap + r * np.column_stack([np.cos(ang), np.sin(ang)])])
ann_x = pos[ANCHOR][0] + ANN_DX
ann_y = pos[ANCHOR][1] + ANN_DY
bw, bh = 0.075, 0.030
bx0 = ann_x if ANN_HA == "left" else (ann_x - bw if ANN_HA == "right" else ann_x - bw / 2)
bx1 = ann_x + bw if ANN_HA == "left" else (ann_x if ANN_HA == "right" else ann_x + bw / 2)
by0 = ann_y if ANN_VA == "bottom" else (ann_y - bh if ANN_VA == "top" else ann_y - bh / 2)
by1 = ann_y + bh if ANN_VA == "bottom" else (ann_y if ANN_VA == "top" else ann_y + bh / 2)
for fx in np.linspace(bx0, bx1, 7):
    for fy in np.linspace(by0, by1, 4):
        avoid_xy = np.vstack([avoid_xy, [fx, fy]])
for t in np.linspace(0.2, 0.8, 4):
    avoid_xy = np.vstack([avoid_xy,
                          [pos[ANCHOR][0] + t * (ann_x - pos[ANCHOR][0]),
                           pos[ANCHOR][1] + t * (ann_y - pos[ANCHOR][1])]])
adjust_text(texts, x=avoid_xy[:, 0], y=avoid_xy[:, 1], ax=ax,
            expand=(1.3, 1.55),
            force_text=(0.6, 0.9), force_static=(0.35, 0.6),
            avoid_self=True, ensure_inside_axes=True)

ax.annotate(
    f"Top enriched\n{ANCHOR}", xy=(pos[ANCHOR][0], pos[ANCHOR][1]),
    xytext=(ann_x, ann_y),
    fontsize=7.5, fontweight="bold", color=ANCHOR_ARROW_COLOR,
    ha=ANN_HA, va=ANN_VA, zorder=5.6,
    path_effects=[pe.withStroke(linewidth=1.8, foreground="white")],
    arrowprops=dict(arrowstyle="-|>", color=ANCHOR_ARROW_COLOR,
                    lw=1.1, mutation_scale=13, shrinkA=2, shrinkB=7),
    annotation_clip=False)

edge_handles = [
    Line2D([0], [0], color=blend(LIGHT_EDGE_STYLE[1][0], LIGHT_EDGE_STYLE[1][2]),
           lw=1.2, label="Hamming distance = 1"),
]
node_handles = [Patch(facecolor=lighten(c), label=l) for l, c in legend_nodes]
marker_kw = dict(linestyle="none", markeredgecolor="#000000", markeredgewidth=0.7)
node_handles.append(Line2D([0], [0], marker="*", markersize=9,
                           markerfacecolor=TCR_COLOR,
                           label=f"Top enriched {ANCHOR}", **marker_kw))
node_handles.append(Line2D([0], [0], marker="o", linestyle="none",
                           markerfacecolor="#9e9e9e", markeredgecolor="white",
                           markersize=7, label=f"With d = 1 neighbour (n = {len(d1_nodes)})"))
node_handles.append(Line2D([0], [0], marker="o", linestyle="none",
                           markerfacecolor="#d6d6d6", markeredgecolor="white",
                           markersize=4, label=f"No d = 1 neighbour (n = {len(plain)})"))
leg1 = ax.legend(handles=edge_handles, title="Edges", loc="center left",
                 bbox_to_anchor=(1.02, 0.76),
                 frameon=True, fontsize=6, title_fontsize=6.5,
                 borderpad=0.6, handlelength=1.8, framealpha=1.0)
leg1.get_frame().set_edgecolor("#cccccc")
ax.add_artist(leg1)
leg2 = ax.legend(handles=node_handles, title="Nodes", loc="center left",
                 bbox_to_anchor=(1.02, 0.36),
                 frameon=True, fontsize=6, title_fontsize=6.5,
                 borderpad=0.6, handlelength=1.5, handletextpad=0.7,
                 labelspacing=0.8, framealpha=1.0)
leg2.get_frame().set_edgecolor("#cccccc")

ax.set_xticks([]); ax.set_yticks([])
for s in ax.spines.values():
    s.set_visible(False)
ax.margins(0.03)

for ext in ("pdf", "svg", "eps", "png"):
    out = os.path.join(SUB, f"peptide_network_{TAG}_dist_eq1_light.{ext}")
    save_retry(fig, out, format=ext, dpi=600 if ext == "png" else None,
               bbox_inches="tight", pad_inches=0.02)
plt.close(fig)
print("saved dist_eq1_light")

print("done")
